import { defineSections } from "../schema";

// Homepage content, in the order the blocks appear on the page.

export const homeSections = defineSections({
  "home.hero": {
    page: "home",
    label: "Openingsbeeld (hero)",
    help: "Het eerste scherm bovenaan de homepage: achtergrondvideo, grote titel, knop en het witte productkaartje rechtsonder.",
    fields: [
      { key: "video", type: "video", label: "Achtergrondvideo", help: "Speelt stil en herhaalt zich achter de titel", default: "/hero/v3-bg.mp4" },
      { key: "poster", type: "image", label: "Foto terwijl video laadt", help: "Wordt getoond tot de video geladen is", default: "/hero/v3-hero.png" },
      { key: "titleLine1", type: "text", label: "Titel — eerste regel", default: "Elke hap" },
      { key: "titleLine2", type: "text", label: "Titel — tweede regel", help: "Naast deze regel staat de oranje ster-sticker", default: "een feest" },
      { key: "burst", type: "text", label: "Tekst in de ster-sticker", help: "Kort houden (1 woord)", default: "VERS!" },
      {
        key: "text",
        type: "textarea",
        label: "Tekst onder de titel",
        default: "Vers gedraaid, goudbruin gebakken. Schuif aan tafel en proef de echte Belgische kroket.",
      },
      { key: "buttonLabel", type: "text", label: "Knoptekst", help: "Oranje knop onder de tekst", default: "Bekijk menu" },
      { key: "buttonHref", type: "url", label: "Knoplink", help: "Leeg laten = knop verbergen", default: "/producten" },
      { key: "cardImage", type: "image", label: "Kaartje — foto", help: "Wit kaartje rechtsonder (niet zichtbaar op gsm)", default: "/ugc/ugc-8.png" },
      { key: "cardTitle", type: "text", label: "Kaartje — titel", default: "Garnaalkroket" },
      { key: "cardButtonLabel", type: "text", label: "Kaartje — knoptekst", default: "Meer info" },
      { key: "cardButtonHref", type: "url", label: "Kaartje — knoplink", help: "Leeg laten = knop verbergen", default: "/producten" },
    ],
  },
  "home.intro": {
    page: "home",
    label: "Over Kroketco (intro)",
    help: "Het witte blok met de grote tekst die woord per woord inkleurt tijdens het scrollen, met twee knoppen ernaast.",
    fields: [
      { key: "eyebrow", type: "text", label: "Klein label", default: "Over Kroketco" },
      {
        key: "parts",
        type: "list",
        label: "Tekst (in stukken)",
        help: "De grote tekst wordt achter elkaar gezet: per stuk eerst de gewone tekst, daarna het oranje gedeelte.",
        itemLabel: "Tekststuk",
        fields: [
          { key: "text", type: "textarea", label: "Gewone tekst", default: "" },
          { key: "accent", type: "text", label: "Oranje tekst erna", help: "Mag leeg blijven", default: "" },
        ],
        default: [
          { text: "Kroketco maakt al meer dan 25 jaar", accent: "ambachtelijke Belgische kroketten." },
          { text: "Vers gedraaid, met de hand gepaneerd en", accent: "goudbruin gebakken" },
          { text: "— voor thuis, de betere traiteur en de horeca in", accent: "heel België." },
        ],
      },
      { key: "button1Label", type: "text", label: "Groene knop — tekst", default: "Meer over ons" },
      { key: "button1Href", type: "url", label: "Groene knop — link", help: "Leeg laten = knop verbergen", default: "/over-ons" },
      { key: "button2Label", type: "text", label: "Oranje knop — tekst", default: "Neem contact op" },
      { key: "button2Href", type: "url", label: "Oranje knop — link", help: "Leeg laten = knop verbergen", default: "/#contact" },
    ],
  },
  "home.video": {
    page: "home",
    label: "Brede video",
    help: "De brede video onder het intro-blok, die meeloopt met het scrollen.",
    fields: [{ key: "video", type: "video", label: "Video", default: "/video/intro.mp4" }],
  },
  "home.features": {
    page: "home",
    label: "Troeven (iconen)",
    help: "De rij iconen met korte tekst onder de brede video.",
    fields: [
      {
        key: "items",
        type: "list",
        label: "Troeven",
        itemLabel: "Troef",
        fields: [
          { key: "icon", type: "image", label: "Icoon", default: "" },
          { key: "label", type: "text", label: "Tekst", default: "" },
        ],
        default: [
          { icon: "/icons/icon-1.png", label: "Lokale producten" },
          { icon: "/icons/icon-2.png", label: "Belgische kazen" },
          { icon: "/icons/icon-3.png", label: "Vers gedraaid" },
          { icon: "/icons/icon-4.png", label: "Gemaakt voor chefs" },
          { icon: "/icons/icon-5.png", label: "Met de hand gemaakt" },
          { icon: "/icons/icon-6.png", label: "Familie recept" },
        ],
      },
    ],
  },
  "home.products": {
    page: "home",
    label: "Assortiment (slider)",
    help: "Het donkergroene blok met de schuivende productkaarten.",
    fields: [
      { key: "eyebrow", type: "text", label: "Klein label", default: "Ons assortiment" },
      { key: "title", type: "text", label: "Titel", default: "Ambachtelijke kroketten voor elk moment." },
      { key: "buttonLabel", type: "text", label: "Knoptekst op elke kaart", default: "Bestel nu" },
      {
        key: "items",
        type: "list",
        label: "Productkaarten",
        itemLabel: "Kaart",
        fields: [
          { key: "name", type: "text", label: "Naam", default: "" },
          { key: "image", type: "image", label: "Foto", default: "" },
          { key: "href", type: "url", label: "Knoplink", help: "Leeg laten = knop verbergen", default: "/producten" },
        ],
        default: [
          { name: "Kaaskroket", image: "/kroketten/prod-kaas.jpg", href: "/producten" },
          { name: "Klassieke kroket", image: "/kroketten/prod-klassiek.jpg", href: "/producten" },
          { name: "Mini garnaal", image: "/kroketten/prod-garnaal.jpg", href: "/producten" },
          { name: "Beertjes", image: "/kroketten/prod-beertjes.jpg", href: "/producten" },
        ],
      },
    ],
  },
  "home.photo": {
    page: "home",
    label: "Grote foto met stickers",
    help: "De volle-breedte foto met schuine stickers, vlak boven de tijdlijn.",
    fields: [
      { key: "image", type: "image", label: "Foto (liggend)", help: "Voor computer, tablet en gsm in liggende stand", default: "/new-image-section/eten-landscape.png" },
      { key: "imagePortrait", type: "image", label: "Foto (staand, gsm)", help: "Formaat 9:16, voor gsm rechtop", default: "/new-image-section/eten-portrait.png" },
      { key: "alt", type: "text", label: "Beschrijving foto", help: "Voor blinden en Google; niet zichtbaar", default: "Vrouw geniet van een krokante ambachtelijke Kroketco kroket" },
      {
        key: "stickers",
        type: "list",
        label: "Stickers",
        help: "Positie en draaiing liggen vast per plaats (1e linksboven, 2e rechtsboven, 3e linksonder).",
        itemLabel: "Sticker",
        fields: [
          { key: "image", type: "image", label: "Sticker-afbeelding", help: "Liefst een PNG met transparante achtergrond", default: "" },
          { key: "alt", type: "text", label: "Tekst op de sticker", help: "Voor blinden en Google; niet zichtbaar", default: "" },
        ],
        default: [
          { image: "/new-image-section/label-lekerrr.png", alt: "Lekkerrr!" },
          { image: "/new-image-section/label-ambachtelijk.png", alt: "Ambachtelijk" },
          { image: "/new-image-section/label-krokant.png", alt: "Krokant!" },
        ],
      },
    ],
  },
  "home.history": {
    page: "home",
    label: "Tijdlijn (ons verhaal)",
    help: "Het groene blok met de jaartallen die op een boog draaien tijdens het scrollen. Staat ook op de pagina Over ons.",
    fields: [
      { key: "eyebrow", type: "text", label: "Klein label", default: "Ons verhaal" },
      { key: "title", type: "text", label: "Titel", default: "Kroketco door de jaren" },
      { key: "image", type: "image", label: "Foto in de ster", help: "Naast de titel, in een stervorm (niet op gsm)", default: "/ugc/ugc-3.png" },
      {
        key: "entries",
        type: "list",
        label: "Mijlpalen",
        itemLabel: "Mijlpaal",
        fields: [
          { key: "year", type: "text", label: "Jaartal", default: "" },
          { key: "tag", type: "text", label: "Label", help: "Kort, in het limoen bolletje", default: "" },
          { key: "text", type: "textarea", label: "Tekst", default: "" },
        ],
        default: [
          { year: "1998", tag: "Het begin", text: "Kroketco start als klein familiebedrijf: vers gedraaide kroketten, met de hand gepaneerd." },
          { year: "2005", tag: "Eigen keuken", text: "We openen onze eigen ambachtelijke keuken, zodat elke kroket met dezelfde zorg gemaakt blijft." },
          { year: "2014", tag: "Nieuwe smaken", text: "Van kaas tot garnaal: het assortiment groeit met zorgvuldig gekozen, streekgebonden recepten." },
          { year: "2020", tag: "Heel België", text: "Kroketco vindt zijn weg naar de betere traiteur en de horeca in heel het land." },
          { year: "2026", tag: "Vandaag", text: "Nog altijd ambachtelijk, nog altijd goudbruin gebakken — elke hap een feest." },
        ],
      },
      { key: "buttonLabel", type: "text", label: "Knoptekst", default: "Bekijk assortiment" },
      { key: "buttonHref", type: "url", label: "Knoplink", help: "Leeg laten = knop verbergen", default: "/producten" },
    ],
  },
  "home.partners": {
    page: "home",
    label: "Partners (groeiende video)",
    help: "Kleine video met partnerlogo's rond; tijdens het scrollen groeit de video en verschijnt de lijst met partners.",
    fields: [
      { key: "title", type: "text", label: "Titel boven de kleine video", default: "Sterk dankzij onze partners" },
      {
        key: "badges",
        type: "list",
        label: "Logo's rond de video",
        help: "Positie en kleur van de ronde badge liggen vast per plaats (max. 7 plaatsen; meer logo's hergebruiken die plaatsen).",
        itemLabel: "Logo",
        fields: [
          { key: "logo", type: "image", label: "Logo", default: "" },
          { key: "name", type: "text", label: "Naam partner", help: "Voor blinden en Google; niet zichtbaar", default: "" },
        ],
        default: [
          { logo: "/partners/logo-steen.3bac4d420028.svg", name: "Steen Food Masters" },
          { logo: "/partners/logo.svg", name: "Duva Fruit" },
          { logo: "/partners/logo-freezcenter.png", name: "Biervliet Freez Center" },
          { logo: "/partners/rafina.svg", name: "Rafina" },
          { logo: "/partners/HUPPA_Logo_Screen_Black_RGB.svg", name: "Huppa" },
          { logo: "/partners/VlaemynckNatuurlijk_logo_header.svg", name: "Vlaemynck Natuurlijk" },
          { logo: "/partners/xfreshbyvero-logo.png.pagespeed.ic.tV35_7rs2f.webp", name: "Fresh by Vero" },
        ],
      },
      { key: "video", type: "video", label: "Video", default: "/video/partners.mp4" },
      { key: "poster", type: "image", label: "Foto terwijl video laadt", default: "/ugc/ugc-3.png" },
      { key: "listTitle", type: "text", label: "Titel in de grote video", default: "Versgroothandels in heel Vlaanderen" },
      {
        key: "partners",
        type: "list",
        label: "Partnerlijst",
        help: "Wordt per 4 getoond en wisselt automatisch van pagina.",
        itemLabel: "Partner",
        fields: [
          { key: "name", type: "text", label: "Naam", default: "" },
          { key: "desc", type: "text", label: "Omschrijving", help: "Groen label rechts (niet op gsm)", default: "" },
        ],
        default: [
          { name: "Steen Food Masters", desc: "Food & non-food" },
          { name: "Huppa", desc: "Oostende & Wortegem-Petegem" },
          { name: "Rafina", desc: "Lauwe · sinds 1954" },
          { name: "Duva Fruit", desc: "Groenten & fruit · Gistel" },
          { name: "Vlaemynck Natuurlijk", desc: "Aardappelproducten · Veurne" },
          { name: "Biervliet Freez Center", desc: "Diepvries · Diksmuide" },
          { name: "Fresh by Vero", desc: "Groenten & fruit · Poperinge" },
        ],
      },
      { key: "listHref", type: "url", label: "Link van elke partnerregel", default: "/partners" },
      { key: "buttonLabel", type: "text", label: "Knoptekst", default: "Ontdek onze partners" },
      { key: "buttonHref", type: "url", label: "Knoplink", help: "Leeg laten = knop verbergen", default: "/partners" },
    ],
  },
  "home.marquee": {
    page: "home",
    label: "Schuivende fotokaarten",
    help: "De rij foto's met een label die vanzelf voorbij schuift, boven het contactformulier. Kaderkleuren liggen vast per plaats.",
    fields: [
      {
        key: "cards",
        type: "list",
        label: "Kaarten",
        itemLabel: "Kaart",
        fields: [
          { key: "image", type: "image", label: "Foto", help: "Staand formaat (3:4)", default: "" },
          { key: "label", type: "text", label: "Label", help: "Kort woord onderaan de kaart", default: "" },
        ],
        default: [
          { image: "/ugc/ugc-2.png", label: "Ambachtelijk" },
          { image: "/ugc/ugc-4.png", label: "Huisgemaakt" },
          { image: "/ugc/ugc-1.png", label: "Romig" },
          { image: "/ugc/ugc-8.png", label: "Goudbruin" },
          { image: "/ugc/ugc-5.png", label: "Krokant" },
          { image: "/ugc/ugc-7.png", label: "Smaakbom" },
          { image: "/ugc/ugc-9.png", label: "Vers" },
          { image: "/ugc/ugc-3.png", label: "Belgisch" },
        ],
      },
    ],
  },
  "home.contact": {
    page: "home",
    label: "Contactblok",
    help: "Onderaan de homepage. De velden van het formulier zelf pas je aan bij Algemeen → Contactformulier.",
    fields: [{ key: "title", type: "text", label: "Titel", default: "Contacteer ons" }],
  },
});
